version: "3.8"

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./requirements/mariadb/conf/my.cnf:/etc/mysql/my.cnf:ro
        #      - ./requirements/mariadb/tools:/docker-entrypoint-initdb.d:ro
    networks:
      - inception_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s # time between each health check
      retries: 5 # number of retries before considered unhealthy
      start_period: 20s # initial grace period after container startup Docker will not check health
      timeout: 20s # time to wait fo a response from health check command

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    depends_on:
      mariadb:
        condition: service_healthy

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - CERTS_=${CERTS_}
    volumes:
      #      - ./requirements/wordpress:/var/www/html:ro
      #      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      #      - ${CERTS_}:/etc/nginx/ssl:ro
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    depends_on:
      - wordpress
    ports:
      - "443:443"

volumes:
  mariadb_data: # volume that contains wordpress database
  wordpress_data: # volume that contains wordpress website files

networks:
  inception_network:
    driver: bridge
